project:
  type: website

website:
  title: "IS415 Project Website"
  navbar:
    left:
      - text: "Project Proposal"
        href: "Project_Proposal/Project_Proposal.html"
      - text: "User Guide"
        href: "User_Guide/User_Guide.html"
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

